// Auto-generated by scripts/export_tinyml_model.py
// Pre-trained commercial building 7x24 baseline mean and standard deviation weekly profiles (kW)
#pragma once
#ifndef EDGE_FORECAST_MODEL_H
#define EDGE_FORECAST_MODEL_H

#define FORECAST_DAYS_IN_WEEK 7
#define FORECAST_HOURS_IN_DAY 24
#define FORECAST_PROFILE_CELLS (FORECAST_DAYS_IN_WEEK * FORECAST_HOURS_IN_DAY)

// Hyperparameters for On-Device Edge Adaptation & Momentum
#define FORECAST_ALPHA_ADAPTATION_RATE 0.15f     // Daily Exponential Moving Average learning rate for mean
#define FORECAST_ALPHA_STD_RATE        0.10f     // Daily learning rate for volatility/std
#define FORECAST_PERSISTENCE_FACTOR    0.60f     // Autoregressive residual persistence factor (phi)
#define FORECAST_MOMENTUM_FACTOR       0.25f     // Rate of change momentum boost factor (phi_v)
#define FORECAST_P95_Z_SCORE           1.645f    // 95% single-sided Gaussian confidence factor
#define FORECAST_MIN_POWER_KW          0.05f     // Minimum floor in kW (prevents negative predictions)
#define FORECAST_MIN_CLAMP_FACTOR      0.20f     // Maximum downward drift allowed (20% of baseline)
#define FORECAST_MAX_CLAMP_FACTOR      3.00f     // Maximum upward drift allowed (300% of baseline)

// Baseline 7x24 weekly mean profile: Row 0 = Monday, Row 6 = Sunday
static const float DEFAULT_WEEKLY_PROFILE[7][24] = {
    // Monday Mean (00:00 to 23:00)
    {4.110f, 3.952f, 3.842f, 3.796f, 3.548f, 3.753f, 3.804f, 4.003f, 4.925f, 5.574f, 5.587f, 5.410f, 5.686f, 5.263f, 5.564f, 6.089f, 5.981f, 5.527f, 5.203f, 5.219f, 5.807f, 4.571f, 4.535f, 4.304f},
    // Tuesday Mean (00:00 to 23:00)
    {3.984f, 3.879f, 3.876f, 3.711f, 3.651f, 3.703f, 3.965f, 3.657f, 4.569f, 4.749f, 4.504f, 4.736f, 4.946f, 5.383f, 5.497f, 5.894f, 5.807f, 5.547f, 5.172f, 5.043f, 5.729f, 4.564f, 4.063f, 4.076f},
    // Wednesday Mean (00:00 to 23:00)
    {3.844f, 3.557f, 3.488f, 3.723f, 3.246f, 3.382f, 3.651f, 3.498f, 4.383f, 4.553f, 4.854f, 5.124f, 5.247f, 5.230f, 5.320f, 5.724f, 5.615f, 5.500f, 5.251f, 4.778f, 5.645f, 4.599f, 4.170f, 4.140f},
    // Thursday Mean (00:00 to 23:00)
    {3.878f, 3.910f, 3.434f, 3.631f, 3.480f, 3.435f, 3.513f, 3.493f, 4.366f, 4.627f, 4.551f, 4.790f, 5.164f, 5.133f, 5.967f, 5.797f, 5.836f, 5.141f, 5.064f, 4.694f, 5.691f, 4.313f, 4.026f, 4.072f},
    // Friday Mean (00:00 to 23:00)
    {4.237f, 3.989f, 3.800f, 3.772f, 3.785f, 3.635f, 3.662f, 3.481f, 4.275f, 4.460f, 4.576f, 4.802f, 5.161f, 5.722f, 6.080f, 6.596f, 6.234f, 6.071f, 5.459f, 5.374f, 6.185f, 4.761f, 4.533f, 4.299f},
    // Saturday Mean (00:00 to 23:00)
    {4.249f, 3.953f, 3.816f, 3.780f, 3.576f, 3.627f, 3.618f, 3.605f, 4.031f, 4.644f, 4.545f, 4.710f, 4.680f, 5.656f, 5.524f, 6.150f, 5.862f, 5.872f, 5.487f, 5.236f, 5.720f, 4.859f, 4.226f, 4.348f},
    // Sunday Mean (00:00 to 23:00)
    {4.276f, 4.094f, 3.848f, 3.923f, 3.488f, 3.492f, 3.413f, 3.567f, 3.739f, 3.640f, 3.819f, 4.233f, 4.751f, 5.121f, 5.577f, 5.707f, 5.877f, 5.790f, 5.729f, 7.731f, 4.941f, 4.680f, 4.389f, 4.391f},
};

// Baseline 7x24 weekly standard deviation profile: Row 0 = Monday, Row 6 = Sunday
static const float DEFAULT_STD_PROFILE[7][24] = {
    // Monday Volatility Sigma (00:00 to 23:00)
    {3.365f, 3.347f, 3.302f, 3.338f, 3.308f, 3.236f, 3.948f, 4.924f, 5.154f, 5.737f, 5.214f, 4.433f, 3.778f, 3.326f, 3.416f, 3.564f, 3.518f, 3.412f, 3.389f, 3.048f, 3.412f, 3.356f, 3.103f, 3.181f},
    // Tuesday Volatility Sigma (00:00 to 23:00)
    {2.963f, 3.171f, 2.984f, 3.111f, 2.988f, 3.106f, 3.722f, 4.413f, 5.420f, 4.661f, 4.040f, 3.267f, 3.179f, 3.332f, 3.189f, 3.453f, 3.332f, 3.350f, 3.160f, 2.883f, 3.276f, 2.965f, 2.917f, 2.748f},
    // Wednesday Volatility Sigma (00:00 to 23:00)
    {2.735f, 2.666f, 2.773f, 2.730f, 2.696f, 2.723f, 3.153f, 3.907f, 4.596f, 4.571f, 3.727f, 3.545f, 3.623f, 2.883f, 3.047f, 3.259f, 3.211f, 3.068f, 3.254f, 2.919f, 3.299f, 3.024f, 2.889f, 3.002f},
    // Thursday Volatility Sigma (00:00 to 23:00)
    {2.861f, 2.846f, 2.900f, 2.991f, 2.867f, 2.924f, 3.193f, 3.803f, 4.215f, 3.886f, 3.192f, 2.948f, 3.452f, 3.450f, 3.539f, 3.631f, 3.397f, 3.310f, 3.256f, 3.105f, 3.507f, 3.222f, 2.792f, 2.946f},
    // Friday Volatility Sigma (00:00 to 23:00)
    {3.296f, 3.221f, 3.297f, 3.234f, 3.319f, 3.155f, 3.076f, 3.022f, 3.374f, 3.466f, 3.460f, 3.435f, 3.796f, 3.910f, 4.253f, 4.095f, 4.098f, 4.278f, 4.085f, 3.702f, 4.011f, 3.682f, 3.577f, 3.475f},
    // Saturday Volatility Sigma (00:00 to 23:00)
    {3.529f, 3.431f, 3.481f, 3.429f, 3.243f, 3.145f, 3.343f, 3.227f, 3.354f, 3.357f, 3.193f, 3.364f, 3.436f, 3.846f, 3.618f, 3.852f, 3.961f, 3.896f, 3.839f, 3.520f, 3.969f, 3.502f, 3.559f, 3.294f},
    // Sunday Volatility Sigma (00:00 to 23:00)
    {3.458f, 3.298f, 3.264f, 3.376f, 3.074f, 3.100f, 3.129f, 3.101f, 3.101f, 2.974f, 3.018f, 3.246f, 3.483f, 3.392f, 3.657f, 3.820f, 3.900f, 3.864f, 3.654f, 12.497f, 3.634f, 3.482f, 3.314f, 3.428f},
};

#endif // EDGE_FORECAST_MODEL_H
