"""Pre-training and exporter script for ESP32 tinyML Edge Forecaster.

Extracts both the 7x24 weekly hourly mean profile matrix (kW) and the 7x24 hourly
standard deviation profile matrix (kW) from the commercial building dataset,
generating `firmware/src/edge_forecast_model.h`.
"""

from __future__ import annotations

import sys
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / ".agents" / "real_data"
OUT_HEADER = ROOT / "firmware" / "src" / "edge_forecast_model.h"

# Default fallback commercial retail profile in kW (used if cache is absent)
FALLBACK_BASE_DAY = [
    4.2, 4.0, 3.9, 4.5, 36.2, 41.8, 39.5, 38.0, 25.4, 16.2,
    15.0, 14.6, 14.1, 14.3, 26.5, 27.2, 18.4, 10.2, 8.1, 6.7,
    5.2, 4.6, 4.3, 4.1,
]


def extract_weekly_profiles(building: str = "Panther_retail_Lester") -> tuple[np.ndarray, np.ndarray]:
    """Extract 7x24 mean and standard deviation profile matrices from BDG2 training data (2016)."""
    csv_path = CACHE / "electricity.csv"
    if not csv_path.exists():
        print(f"Warning: {csv_path} not found. Generating synthesized retail profile.")
        mean_profile = np.zeros((7, 24), dtype=float)
        std_profile = np.zeros((7, 24), dtype=float)
        for day in range(7):
            factor = 0.65 if day == 6 else (0.80 if day == 5 else 1.0)
            mean_profile[day] = np.array(FALLBACK_BASE_DAY) * factor
            std_profile[day] = np.maximum(0.5, mean_profile[day] * 0.15)
        return mean_profile, std_profile

    print(f"Loading 2016 data for {building} from {csv_path}...")
    df = pd.read_csv(csv_path, usecols=["timestamp", building], index_col="timestamp", parse_dates=True)
    df_2016 = df.loc["2016-01-01":"2016-12-31", building].dropna()
    valid = df_2016[df_2016 > 0.0]

    grouped_mean = valid.groupby([valid.index.dayofweek, valid.index.hour]).mean()
    grouped_std = valid.groupby([valid.index.dayofweek, valid.index.hour]).std().fillna(1.0)

    mean_profile = np.zeros((7, 24), dtype=float)
    std_profile = np.zeros((7, 24), dtype=float)

    for day in range(7):
        for hour in range(24):
            if (day, hour) in grouped_mean.index:
                mean_profile[day, hour] = float(grouped_mean.loc[(day, hour)])
                std_val = float(grouped_std.loc[(day, hour)])
                std_profile[day, hour] = max(0.20, std_val)
            else:
                mean_profile[day, hour] = float(valid.mean())
                std_profile[day, hour] = float(valid.std())

    return mean_profile, std_profile


def generate_header(mean_profile: np.ndarray, std_profile: np.ndarray, out_path: Path) -> None:
    """Generate the C++ header file with dual matrices and momentum parameters."""
    lines = [
        "// Auto-generated by scripts/export_tinyml_model.py",
        "// Pre-trained commercial building 7x24 baseline mean and standard deviation weekly profiles (kW)",
        "#pragma once",
        "#ifndef EDGE_FORECAST_MODEL_H",
        "#define EDGE_FORECAST_MODEL_H",
        "",
        "#define FORECAST_DAYS_IN_WEEK 7",
        "#define FORECAST_HOURS_IN_DAY 24",
        "#define FORECAST_PROFILE_CELLS (FORECAST_DAYS_IN_WEEK * FORECAST_HOURS_IN_DAY)",
        "",
        "// Hyperparameters for On-Device Edge Adaptation & Momentum",
        "#define FORECAST_ALPHA_ADAPTATION_RATE 0.15f     // Daily Exponential Moving Average learning rate for mean",
        "#define FORECAST_ALPHA_STD_RATE        0.10f     // Daily learning rate for volatility/std",
        "#define FORECAST_PERSISTENCE_FACTOR    0.60f     // Autoregressive residual persistence factor (phi)",
        "#define FORECAST_MOMENTUM_FACTOR       0.25f     // Rate of change momentum boost factor (phi_v)",
        "#define FORECAST_P95_Z_SCORE           1.645f    // 95% single-sided Gaussian confidence factor",
        "#define FORECAST_MIN_POWER_KW          0.05f     // Minimum floor in kW (prevents negative predictions)",
        "#define FORECAST_MIN_CLAMP_FACTOR      0.20f     // Maximum downward drift allowed (20% of baseline)",
        "#define FORECAST_MAX_CLAMP_FACTOR      3.00f     // Maximum upward drift allowed (300% of baseline)",
        "",
        "// Baseline 7x24 weekly mean profile: Row 0 = Monday, Row 6 = Sunday",
        "static const float DEFAULT_WEEKLY_PROFILE[7][24] = {",
    ]

    day_names = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    for d, name in enumerate(day_names):
        row_values = ", ".join(f"{mean_profile[d, h]:.3f}f" for h in range(24))
        lines.append(f"    // {name} Mean (00:00 to 23:00)")
        lines.append(f"    {{{row_values}}},")
    lines.append("};")
    lines.append("")

    lines.append("// Baseline 7x24 weekly standard deviation profile: Row 0 = Monday, Row 6 = Sunday")
    lines.append("static const float DEFAULT_STD_PROFILE[7][24] = {")
    for d, name in enumerate(day_names):
        row_values = ", ".join(f"{std_profile[d, h]:.3f}f" for h in range(24))
        lines.append(f"    // {name} Volatility Sigma (00:00 to 23:00)")
        lines.append(f"    {{{row_values}}},")
    lines.append("};")
    lines.append("")

    lines.append("#endif // EDGE_FORECAST_MODEL_H")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated dual-matrix header: {out_path}")


def main():
    mean_prof, std_prof = extract_weekly_profiles()
    generate_header(mean_prof, std_prof, OUT_HEADER)


if __name__ == "__main__":
    main()
